"""Apply the predeclared policy and render the complete human-readable report."""
import json, csv, math, hashlib
from datetime import datetime,timezone,timedelta
from pathlib import Path
import numpy as np
from analyze import ROOT,OUT,SEED,BASE,NAMES,save,csvsave,indicator

def load(name): return json.loads((OUT/name).read_text(encoding='utf-8'))
def csvload(name): return list(csv.DictReader((OUT/name).open(encoding='utf-8')))
def f(x,n=3): return f'{float(x):.{n}f}'
def ticket(c): return ' – '.join(f'{v:02}' for v in c['numbers'])
def table(headers,rows):
    return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']*len(headers))+'|']+['| '+' | '.join(map(str,r))+' |' for r in rows])

audit=load('audit.json'); meta=load('analysis_metadata.json'); baseline=load('baseline.json'); models=load('model_performance.json'); candidates=load('candidates.json'); jev=load('jev_response.json'); answers=jev['answers']; sens=csvload('sensitivity.csv')
assert jev['model'].startswith('jev-') and len(answers)==141
confirmation={r['model']:r for r in models if r['period']=='confirmation'}
qualifiers=meta['qualifying_models']; ranked=[]
advmax=max([max(confirmation[m]['delta_random'],0) for m in qualifiers],default=0)
for c in candidates:
    a={key:answers[f'{c["id"]}_{key}'] for key in ['robustness','consensus','quality','overfit','stable','stronger','dependent']}
    validated=max([max(confirmation[m]['delta_random'],0) for m in c['validated_models']],default=0)/(advmax or 1)
    policy_score=.35*validated+.20*c['sensitivity_top_quartile_fraction']+.10*(20-c['ensemble_rank'])/19+.10*a['robustness']['score']/4+.05*a['consensus']['score']/4+.10*a['quality']['score']/4+.10*answers['overall']['probabilities'][c['id']]-.10*a['overfit']['noul']-.05*a['dependent']['noul']
    eligible=bool(c['validated_models'] and a['stronger']['noul']>=.5 and a['stable']['noul']>=.5)
    ranked.append(dict(**c,policy_score=policy_score,eligible=eligible,jev_choice_probability=answers['overall']['probabilities'][c['id']],jev={k:v for k,v in a.items()}))
ranked.sort(key=lambda c:(-c['policy_score'],c['id']))
eligible=[c for c in ranked if c['eligible']]
if qualifiers and eligible:
    primary=eligible[0]; remaining=eligible[1:6]
    if not remaining: remaining=[c for c in ranked if c['id']!=primary['id']][:5]
    secondary=min(remaining,key=lambda c:(len(set(c['numbers'])&set(primary['numbers'])),-c['policy_score'],c['id']))
    reason='Qualified empirical support and Jev risk checks; predeclared composite ranking.'
else:
    # Uniform seeded candidate selection, with minimum-overlap secondary.
    rng=np.random.default_rng(SEED); ordered=sorted(ranked,key=lambda c:c['id']); primary=ordered[int(rng.integers(len(ordered)))]; remaining=[c for c in ordered if c['id']!=primary['id']]
    overlap=min(len(set(c['numbers'])&set(primary['numbers'])) for c in remaining)
    diverse=[c for c in remaining if len(set(c['numbers'])&set(primary['numbers']))==overlap]
    secondary=diverse[int(rng.integers(len(diverse)))]; reason='No methodology passed the corrected confirmation edge gate. Seeded uniform selection among the candidates, then minimum-overlap diversification. No predictive superiority claimed.'
decision=dict(created_utc=datetime.now(timezone.utc).isoformat(),seed=SEED,cutoff_draw=meta['last']['draw_id'],cutoff_date=meta['last']['date'],target_draw=meta['next_draw_id'],primary={k:primary[k] for k in ['id','numbers','generator']},secondary={k:secondary[k] for k in ['id','numbers','generator']},overlap=len(set(primary['numbers'])&set(secondary['numbers'])),rule=reason,jev_choice=answers['overall'],conclusion=meta['conclusion'],individual_ticket_jackpot_probability=1/baseline['total_combinations'],two_distinct_ticket_jackpot_probability=2/baseline['total_combinations'],note='Combined jackpot probability is 2/C(38,6) for any two distinct tickets; low overlap changes coverage/dependence, not this jackpot probability.')
save('final_decision.json',decision)
flat=[]
for c in sorted(ranked,key=lambda c:c['id']):
    r=dict(id=c['id'],numbers=c['numbers'],generator=c['generator'],choice_probability=c['jev_choice_probability'],policy_score=c['policy_score'],eligible=c['eligible'])
    for k,v in c['jev'].items():
        r[k]=v.get('score',v.get('noul')); r[f'{k}_confidence']=v.get('confidence')
    flat.append(r)
csvsave('jev_candidate_summary.csv',flat); save('ranked_candidates.json',ranked)
numbers=csvload('number_statistics.csv'); pairs=csvload('pair_statistics.csv'); conditionals=csvload('conditional_statistics.csv'); structure=load('structure_summary.json'); random=load('randomness.json'); verify=load('verification.json')
oldmodels={r['model']:r for r in models if r['period']=='all'}
datedraws=json.loads((ROOT/'data/draws.json').read_text()); draws=np.array([r['numbers'] for r in datedraws])-1; a=indicator(draws)
lagrows=[]
for j in range(38):
    r={'number':j+1}
    for lag in [1,2,3,5]: r[f'lag{lag}_correlation']=float(np.corrcoef(a[:-lag,j],a[lag:,j])[0,1])
    lagrows.append(r)
csvsave('number_autocorrelations.csv',lagrows)
gapstats='Current gap counts draws since the last appearance (zero if drawn most recently). Completed gaps count intervening absent draws; left/right censored gaps are excluded from completed-gap summaries. Longest observed absence includes boundary runs. Finite-window censoring is retained in the Monte Carlo gap test. Frequency volatility is the standard deviation of appearance rates in complete 10-draw blocks.'
ap_random=5/37+(32/37)*sum(1/i for i in range(1,39))/38
sections=[]
sections.append(f'# Jamaica Lotto experimental decision report\n\n**Conclusion: {meta["conclusion"]}.**\n\n**Primary pick: {ticket(primary)} ({primary["id"]})**\n\n**Secondary pick: {ticket(secondary)} ({secondary["id"]})**\n\nThese are disciplined diversified selections, not statistically superior tickets. Latest observed draw: #{meta["last"]["draw_id"]}, {meta["last"]["date"]}. Intended next draw: #{meta["next_draw_id"]} on September 19, 2026, provided it has not already occurred. This saved report is a fixed snapshot; refresh the archive before using it for a later draw.\n\n{reason} The picks share {decision["overlap"]} numbers. Under the uniform model each ticket has a jackpot chance of 1 in {baseline["total_combinations"]:,}; any two distinct tickets have combined probability 2/{baseline["total_combinations"]:,}.')
sections.append('## 1. Dataset audit\n\n'+table(['Check','Result'],[['Workbook found','Lotto-Draw-Dataset.xlsx; requested (1) variant not present'],['Original records',audit['original_draws']],['Original range',f'#{audit["first_draw"]}–#{audit["last_draw"]}; {audit["first_date"]}–{audit["last_date"]}'],['Source range','Lotto Draws!A6:J172'],['Order','Strictly descending dates and IDs; analysis reverses to ascending'],['Missing IDs','2252–2261'],['Duplicate IDs / duplicate records','0 / 0'],['Missing cells / malformed dates','0 / 0'],['Invalid main / bonus numbers','0 / 0'],['Repeated main numbers / bonus-main overlap','0 / 0'],['Six main numbers present','All records'],['Valid range','Main and bonus 1–38; all observed bonus balls distinct from main balls'],['Unexpected weekdays','0; Wednesday/Saturday'],['Source conflicts in fetched overlap','0; #2262 and #2337 agree'],['Merged analysis records',f'{audit["analysis_draws"]}; consecutive #2161–#2338'],['Original unchanged','SHA-256 verified after analysis']])+f'\n\nOriginal SHA-256: `{audit["sha256"]}`. Original source labels refer to an earlier workbook and two screenshots; most original rows have not been independently reverified against primary records. Auditing validity does not prove historical source accuracy.')
sections.append('## 2. Missing and new draws recovered\n\n'+table(['Draw','Date','Main numbers','Bonus'],[[r['draw_id'],r['date'],', '.join(map(str,r['numbers'])),r['bonus']] for r in audit['official_additions']])+ '\n\nSource: [Supreme Ventures official past-results page](https://supremeventures.com/past-results/). Its public JavaScript directs results requests to `https://test-results.supremeventures.com/public/game/5/from/{start}/to/{end}` with a ten-day limit. The host name contains “test”, but this is the feed used by the official public site, not an invented endpoint. Raw successful archive responses are retained in `data/official-YYYY-MM-DD.json`. Queries covered November 19–December 24, 2025 and September 12–19, 2026. Latest returned result was #2338; no #2339 was returned at retrieval. External additions are separate in `data/external_draws.json`; no guessed rows. Official overlap checks corroborated #2262 and #2337. The full original workbook was not overwritten.\n\n[Official rules](https://supremeventures.com/game/lotto/) specify six numbers from 1–38, Wednesday/Saturday at 8:25 PM Jamaica time. Bonus is recorded separately and is excluded from all six-main-number match scores; payout/return-on-money modelling is outside this experiment.')
sections.append('## 3. Exact random baseline\n\nFor k matches: **P(M=k) = C(6,k) C(32,6−k) / C(38,6)**. Expected matches = **36/38 = 0.947368**.\n\n'+table(['Matches','Probability','Percentage'],[[k,f(p,10),f(p*100,6)+'%'] for k,p in enumerate(baseline['match_probabilities'])])+f'\n\nAt least two matches occur naturally on {baseline["probability_at_least_two"]*100:.2f}% of random tickets; at least three on {baseline["probability_at_least_three"]*100:.2f}%. Across 128 trials, approximately {128*baseline["probability_at_least_three"]:.2f} results with three or more matches are expected. Occasional two- or three-match tickets are not evidence of useful prediction.')
sections.append('## 4. Exploratory statistics and draw structure\n\nEach of the 38 main numbers has expected full-history count **28.1053** in 178 draws. `number_statistics.csv` includes all requested rolling frequencies (100/50/30/20/10), EW frequency (half-life 20), counts, deviations, gap summaries, trend, short/long ratio and block volatility.\n\n'+gapstats+'\n\nMost frequent numbers (descriptive only):\n\n'+table(['Number','Count','Expected','Holm p'],[[r['number'],r['frequency'],f(r['expected']),f(r['frequency_holm_p'])] for r in sorted(numbers,key=lambda r:-int(r['frequency']))[:8]])+'\n\nDraw-level sum, mean, median, extrema, range, parity, low/high (1–19/20–38), bands (1–10/11–20/21–30/31–38), adjacency, spacing, repeated numbers from preceding 1/2/3/5 draws, last digits and clustering (sorted gaps ≤2) are in `draw_structure.csv`.\n\n'+table(['Property','Observed mean','Random mean (200,000 tickets)'],[[r['feature'],f(r['observed_mean']),f(r['random_mean'])] for r in structure['features']])+'\n\nExpected counts per draw in the four bands are 1.579/1.579/1.579/1.263, reflecting unequal band sizes. Last digits 0 and 9 each cover three numbers; the other digits cover four. Common sums/parities occupy more combinations, but no particular combination gains probability because it looks typical. The structural model tests the hypothesis rather than assuming it.')
sections.append('## 5. Relationships and randomness tests\n\nAll 703 pairs are enumerated. Expected count per pair = 178×30/(38×37) = **3.798**. Pair lift relative to uniform and empirical marginal rates, exact enrichment p-values, Holm/BH correction, recency, last-50/100 and half-period counts are saved.\n\n'+table(['Pair test summary','Count'],[['Raw pair p < .05',sum(float(r['p_enrichment'])<.05 for r in pairs)],['Pair Holm p < .05',sum(float(r['holm_p'])<.05 for r in pairs)],['Pair BH q < .05',sum(float(r['bh_q'])<.05 for r in pairs)],['Marginal number Holm p < .05',sum(float(r['frequency_holm_p'])<.05 for r in numbers)],['Ordered transition Holm p < .05',sum(float(r['holm_p'])<.05 for r in conditionals)]])+ '\n\nAll 8,436 triples are counted, but each has expected count only about 0.422. Triple findings are descriptive; this sample cannot sustain reliable triple-specific predictive estimation. The 1,444 ordered previous-number → next-number relationships use exact conditional hypergeometric enrichment tests (Fisher upper tail) and Holm correction. Number-level lag-1/2/3/5 correlations are also saved.\n\n10,000 synthetic histories, each 178 independent uniform six-without-replacement draws, calibrate the following diagnostics. Simulations preserve within-draw dependence and finite-window gap censoring. P-values include the +1 Monte Carlo correction; resolution is 1/10,001. Holm correction covers these 14 tests.\n\n'+table(['Test','Observed','Null mean','MC p','Holm p'],[[r['test'],f(r['observed']),f(r['null_mean']),f(r['p_mc'],4),f(r['holm_p'],4)] for r in random['tests']])+'\n\nNo global test provides statistically meaningful or even nominal p<.05 evidence here. These results are consistent with randomness, not proof that every possible dependence is absent. Pair simulations assess both aggregate dispersion and the largest observed pair count; rare-cell Pearson statistics are calibrated by simulation rather than a naive chi-square reference.')
descs=['Smoothed full-history number frequency','Half last-30 rate + half EW rate, half-life 20','Current absence/gap; explicit overdue hypothesis','Last-20 appearance rate minus preceding-40','Training-only Holm-significant pair lift; uniform fallback if none','Smallest standardized distance from training structure','A–F objective combination with earlier-OOS-learned weights','Separate uniformly random six-number control']
sections.append('## 6. Models and strict walk-forward design\n\n'+table(['Model','Definition'],zip(NAMES,descs))+'\n\nEach historical origin starts with at least 50 past draws. A–G optimize their combination-level objective over a common seeded pool of 512 uniform combinations; H is independently sampled. Each prediction, training cutoff, realized outcome and ensemble weight is saved in `walk_forward_predictions.json`. Features, normalization, significance thresholds and ensemble history use the training prefix only.\n\nThere are **128 out-of-sample origins**, split into 88 development and the last 40 confirmation draws. G uses positive earlier-OOS excess over the baseline, shrunk with 20 baseline pseudo-draws; if all excesses vanish it uses equal weights. Its weights are frozen before the confirmation period, while model features update causally. No test-period winner is chosen merely on raw score.\n\nThe protocol was written before calculating performance and before Jev. This remains a retrospective experiment, not a prospectively preregistered trial. Candidate variants and the Jev decision layer are not backtested systems. The final candidate search uses 4,096 combinations to obtain diversity, versus 512 per historical origin; it does not inherit validated performance automatically.')
sections.append('## 7. Walk-forward results\n\nRandom expected matches: **0.947368 per draw** in every table.\n\n'+table(['Model','All 128 mean','All total','All Holm p','Confirm 40 mean','95% block CI','Confirm Holm p'],[[m,f(oldmodels[m]['mean']),oldmodels[m]['total_matches'],f(oldmodels[m]['holm_p']),f(confirmation[m]['mean']),f'{f(confirmation[m]["block95"][0])}–{f(confirmation[m]["block95"][1])}',f(confirmation[m]['holm_p'])] for m in NAMES])+'\n\nThe full-period raw leader is trend (D); the confirmation raw leader is long-term frequency (A). Neither passes corrected validation. The ensemble also fails to exceed the expected random mean in confirmation. **No method qualifies for predictive use.**\n\nConfirmation match distributions:\n\n'+table(['Model','0','1','2','3','4+','Best','Older 20 mean','Recent 20 mean'],[[m,*[f(v,1)+'%' for v in confirmation[m]['percentages'][:4]],f(confirmation[m]['four_plus_pct'],1)+'%',confirmation[m]['best'],f(confirmation[m]['older_half_mean']),f(confirmation[m]['recent_half_mean'])] for m in NAMES])+f'\n\nFull period ranking diagnostics are in `model_performance.csv`: average precision over all 38 numbers and recall@12. Random-ranking expectations are AP ≈ {ap_random:.4f}, recall@12 = {12/38:.4f}. Structure has no unique individual-number ranking; pair rankings are omitted when the pair objective is flat. G’s individual ranking is a marginal proxy and excludes the structure component. Ranking metrics are descriptive, not additional validated edges.\n\nExact one-sided p-values convolve the hypergeometric PMF once per target draw. This is valid under the independent uniform null even for a causally adaptive ticket: conditional on the past, every valid ticket has the same match law. A separate 20,000-replicate random-control simulation cross-checks means. CIs include ordinary bootstrap and circular five-draw block bootstrap (10,000 replicates); the edge gate uses the block lower bound. Small samples and overlapping model histories limit precision.')
sections.append('## 8. Sensitivity and ensemble stability\n\nFourteen reruns change windows (20/40), decay (10/40), trend spans (10/30), pair correction thresholds (.01/.10), training warmup (40/60), history cap (100), ensemble weights (equal/more shrinkage), or the pool seed. Baseline definitions are not replaced by the best sensitivity result.\n\n'+table(['Model','Confirmation mean range','Smallest Holm p','Mean ticket overlap range'],[[m,f'{min(float(r["confirmation_mean"]) for r in sens if r["model"]==m):.3f}–{max(float(r["confirmation_mean"]) for r in sens if r["model"]==m):.3f}',f(min(float(r['confirmation_holm_p']) for r in sens if r['model']==m)),f'{min(float(r["mean_ticket_overlap"]) for r in sens if r["model"]==m):.2f}–{max(float(r["mean_ticket_overlap"]) for r in sens if r["model"]==m):.2f}'] for m in NAMES])+'\n\nNo sensitivity run produces a corrected confirmation edge. Low ticket overlap across some perturbations shows that exact combinations can move substantially even when aggregate performance is similar. Candidate-specific perturbed ranks and top-quartile fractions are saved. Neutral ranks for uniform fallbacks are not counted as stability. An original-only source ablation for A/B/D is saved separately; gaps prevent interpreting its omitted records as consecutive observations. That ablation is exploratory and is not used to select a model.\n\nThe final choice under the no-edge branch is governed by a seed and coverage; it is not a stable statistical optimum. Changed candidate-generation assumptions can change the ticket, which is expected when no winning-probability difference is established.')
sections.append('## 9. Candidate shortlist and Jev Choice\n\nTwenty tickets were generated with no more than three shared numbers between any two. Evidence profiles include individual scores, contributing models, ensemble score, frequency/gap/trend/pair/structure summaries, overlap, method support, sensitivity and counterevidence. These are exploratory combinations, not 20 separately validated strategies.\n\n'+table(['ID','Numbers','Generator','Jev Choice probability','Robustness /4','Evidence quality /4'],[[c['id'],ticket(c),c['generator'],f(c['jev_choice_probability']*100,1)+'%',f(c['jev']['robustness']['score'],2),f(c['jev']['quality']['score'],2)] for c in sorted(ranked,key=lambda c:c['id'])])+f'\n\nJev model: **{jev["model"]}**, requested through `jev-latest`. One request answered **141 questions**: 1 Choice, 60 Scores, 80 Nouls. Usage: **{jev["usage"]["input_tokens"]:,} input / {jev["usage"]["output_tokens"]:,} output tokens**. Choice winner: **{answers["overall"]["choice"]}**, probability **{answers["overall"]["probabilities"][answers["overall"]["choice"]]:.2f}**, confidence **{answers["overall"]["confidence"]:.2f}**.\n\nThe forced Choice result is highly concentrated even though the same response gives almost no support for a predictive advantage. This is a limitation of using a forced qualitative choice in statistically indistinguishable cases. **0.90 is not a 90% chance of winning and not a calibrated probability of a lottery edge.** The deterministic gate prevents this preference from overriding negative statistical evidence.')
sections.append('## 10. Jev Scores and Noul risk checks\n\nRobustness levels range from no support beyond random, through weak/fragile and repeatable-but-uncertain support, to corrected multi-test and unusually robust independently replicated support. Consensus counts independently validated approaches, not correlated unvalidated agreement. Evidence quality scores the quality of positive evidence for an advantage; a rigorous negative experiment is not positive evidence. Exact descriptions are saved in `jev_request.json`.\n\n'+table(['ID','Consensus /4','Overfit/chance Noul','Stable Noul','Stronger than random Noul','Single-model Noul'],[[c['id'],f(c['jev']['consensus']['score'],2),f(c['jev']['overfit']['noul'],2),f(c['jev']['stable']['noul'],2),f(c['jev']['stronger']['noul'],2),f(c['jev']['dependent']['noul'],2)] for c in sorted(ranked,key=lambda c:c['id'])])+'\n\n`jev_response.json` preserves every score, score-level distribution, confidence, Noul and token usage. Noul is a yes-probability judgment with no separate confidence. These model judgments, especially causal “overfit” judgments, are not independently calibrated statistical tests. The full request supplies already-computed statistics; Jev did not calculate them. See [TypeSafe Score](https://docs.typesafe.ai/primitives/score), [Noul](https://docs.typesafe.ai/primitives/noul), and [composite scoring](https://docs.typesafe.ai/patterns/composite-scoring).')
sections.append(f'## 11. Final decision and reasons\n\n**Primary: {ticket(primary)} ({primary["id"]}; generator {primary["generator"]}).** Selected by the reproducible no-edge policy from the diverse shortlist. This selection has no demonstrated predictive advantage.\n\n**Secondary: {ticket(secondary)} ({secondary["id"]}; generator {secondary["generator"]}).** Selected from the minimum-overlap alternatives; shared numbers: {decision["overlap"]}. Diversification changes coverage, not the per-ticket chance.\n\nJev’s preferred candidate **C02: 02 – 10 – 13 – 18 – 24 – 33** remains available for comparison, but does not pass the empirical gate. Its confirmation generator is merely the highest raw mean, with corrected p=0.846.\n\nNext candidates by the predeclared hypothetical policy score (analysis only; not valid edge ranks):\n\n'+table(['ID','Numbers','Policy score','Eligible'],[[c['id'],ticket(c),f(c['policy_score']),c['eligible']] for c in ranked[:5]])+'\n\nThe policy was documented before the Jev request: corrected confirmation p<.05, block-CI lower bound above random, both halves above random, then empirical/sensitivity/Jev weighting if support exists. Otherwise seeded diversification applies. All candidates fail the empirical gate; numerical differences in heuristic or Jev scores cannot rescue them.')
sections.append('## 12. Reality check, verification and update files\n\n**Did we discover an out-of-sample statistical edge over random selection? No detectable edge in this dataset.**\n\nThis is a small-data negative result across the declared tests, not a proof that every future model must fail. There is no evidence here supporting higher winning probabilities for the final tickets. The next useful evidence is prospective recorded performance, with fixed rules and no retrospective changes.\n\nVerification passed: original SHA-256 unchanged; exact PMF normalized and mean reconciled; all predictions contain six distinct legal numbers; every stored match count independently recomputed; historical cutoff precedes target; future-outcome mutation leaves earlier predictions unchanged; confirmation ensemble weights frozen; uniform sampler agrees with the exact baseline.\n\nReusable entry point: `./run.ps1` rebuilds deterministic results from saved data and reuses the saved Jev response only when evidence is unchanged; `./run.ps1 -Refresh -AskJev` fetches new official results, reruns analysis and requests a fresh Jev review. Credentials are read from the environment without logging. Do not treat the snapshot as current after new draws.\n\nMachine-readable outputs include audit, normalized/provenanced draws, baseline, number/pair/triple/conditional statistics, structural statistics, all predictions, performance, sensitivity, candidate evidence, full Jev request/response, and final decision. Model and request hashes are retained. See `README.md` for commands and scope. No original Excel cells were changed.')
report='\n\n'.join(sections)+'\n'
# Snapshot labels must move with refreshed data; do not carry old dates or counts forward.
target_date=datetime.fromisoformat(meta['last']['date'])+timedelta(days=1)
while target_date.weekday() not in (2,5): target_date+=timedelta(days=1)
total_tests=oldmodels[NAMES[0]]['n']; development_tests=total_tests-40
choice_candidate=next(c for c in candidates if c['id']==answers['overall']['choice'])
all_leader=max(oldmodels.values(),key=lambda r:r['mean'])
confirmation_leader=max(confirmation.values(),key=lambda r:r['mean'])
report=report.replace('on September 19, 2026',f'on {target_date:%B %d, %Y}')
report=report.replace('consecutive #2161–#2338',f'consecutive #{meta["first"]["draw_id"]}–#{meta["last"]["draw_id"]}')
report=report.replace('Latest returned result was #2338; no #2339 was returned at retrieval.',f'Latest returned result was #{meta["last"]["draw_id"]}; no #{meta["next_draw_id"]} was returned at retrieval.')
report=report.replace('**28.1053** in 178 draws',f'**{meta["n"]*6/38:.4f}** in {meta["n"]} draws')
report=report.replace('178×30/(38×37) = **3.798**',f'{meta["n"]}×30/(38×37) = **{meta["n"]*30/(38*37):.3f}**')
report=report.replace('only about 0.422',f'only about {meta["n"]*20/math.comb(38,3):.3f}')
report=report.replace('each 178 independent',f'each {meta["n"]} independent')
report=report.replace('Across 128 trials',f'Across {total_tests} trials').replace('approximately 4.95 results',f'approximately {total_tests*baseline["probability_at_least_three"]:.2f} results')
report=report.replace('**128 out-of-sample origins**, split into 88 development',f'**{total_tests} out-of-sample origins**, split into {development_tests} development')
report=report.replace('All 128 mean',f'All {total_tests} mean')
report=report.replace('The full-period raw leader is trend (D); the confirmation raw leader is long-term frequency (A). Neither passes corrected validation. The ensemble also fails to exceed the expected random mean in confirmation. **No method qualifies for predictive use.**',f'The full-period raw leader is {all_leader["model"]}; the confirmation raw leader is {confirmation_leader["model"]}. Qualifying methodologies: {", ".join(qualifiers) or "none"}. Ensemble confirmation mean: {confirmation["G_ensemble"]["mean"]:.3f} versus random {BASE:.3f}. Raw rank alone does not establish an edge.')
report=report.replace('Jev’s preferred candidate **C02: 02 – 10 – 13 – 18 – 24 – 33** remains available for comparison, but does not pass the empirical gate. Its confirmation generator is merely the highest raw mean, with corrected p=0.846.',f'Jev’s preferred candidate **{choice_candidate["id"]}: {ticket(choice_candidate)}** remains available for comparison. Its generator has confirmation Holm p={confirmation[choice_candidate["generator"]]["holm_p"]:.3f}. The empirical gate, not forced Choice probability, determines eligibility.')
report=report.replace('All candidates fail the empirical gate; numerical differences in heuristic or Jev scores cannot rescue them.',f'{sum(c["eligible"] for c in ranked)} candidates meet all empirical/Jev eligibility requirements. Numerical differences in heuristic scores cannot replace corrected evidence.')
if any(r['p_mc']<.05 for r in random['tests']):
    report=report.replace('No global test provides statistically meaningful or even nominal p<.05 evidence here. These results are consistent with randomness, not proof that every possible dependence is absent.',f'{sum(r["p_mc"]<.05 for r in random["tests"])} global tests have nominal p<.05; {sum(r["holm_p"]<.05 for r in random["tests"])} survive Holm correction. Consult the table; statistical anomalies alone do not establish forecast ability.')
if any(float(r['confirmation_holm_p'])<.05 for r in sens):
    report=report.replace('No sensitivity run produces a corrected confirmation edge.','Some exploratory sensitivity tests have corrected p<.05; they cannot be selected post hoc as a new validated baseline.')
report=report.replace('**Did we discover an out-of-sample statistical edge over random selection? No detectable edge in this dataset.**',f'**Did we discover an out-of-sample statistical edge over random selection? {meta["conclusion"]}.**')
(OUT/'REPORT.md').write_text(report,encoding='utf-8')
print(json.dumps(decision,indent=2)); print('Report saved:',OUT/'REPORT.md')
