"""Render two separate reports from completed, immutable-input analyses."""
import json,csv,math
from pathlib import Path
from common import table
R=Path(__file__).resolve().parents[2]
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def pct(x):return f'{100*x:.2f}%'
def num(x):return f'{x:.3f}'
def ci(x):return '–'.join(num(v) for v in x)
def ticket(v):return ' · '.join(f'{x:02}' for x in v)
def write(p,sections):p.write_text('\n\n'.join(sections)+'\n',encoding='utf-8')

def lotto():
    o=R/'results/lotto';s=load(o/'forensic_summary.json');ev=load(o/'hit_miss_predraw_evidence.json');cp=load(o/'construction_performance.json');rc=load(o/'ranking_coverage.json');rnd=load(o/'random_controls.json')
    models=['A_long','B_recent','C_gap','D_trend','G_marginal_proxy']
    def rank(n,m):
        r=next(r for r in s['winning_ranks'] if r['number']==n and r['model']==m)
        return str(r['rank_min']) if r['rank_min']==r['rank_max'] else f"{r['rank_min']}–{r['rank_max']}"
    def cov(m,k):
        r=next(r for r in s['coverage'] if r['model']==m and r['pool']==k)
        return str(r['minimum_winners']) if r['minimum_winners']==r['maximum_winners'] else f"{r['minimum_winners']}–{r['maximum_winners']}"
    out=['# LOTTO #2339 FORENSIC RESULTS',
    'Official main outcome: **01 · 04 · 06 · 13 · 23 · 28**, bonus 20, September 19, 2026. Frozen V1 primary matched **01, 04, 13**. All original V1 files passed SHA-256 preservation checks. The ledger records this outcome against frozen artifacts without inventing earlier registration events. Source: [Supreme Ventures results](https://supremeventures.com/past-results/), archived official-current.json.',
    '## Finding and evidence limits',
    '**The result is compatible with ordinary random variation; no tested refinement justifies V2.** The primary was selected using the existing seeded no-edge policy, not by selecting the six highest marginal scores. Three hits therefore do not validate the ranking model. No next Lotto ticket was generated.',
    s['ranking_limit']+' These are reproducible pre-draw **score-rank reconstructions**, not newly recovered saved ranks. Every reconstructed stored candidate score reconciled with the saved pre-draw score. #2339 was excluded from all fitting. G is a marginal proxy and omits the non-additive structure objective. E_pairs is flat after training correction; F_structure ranks combinations, not individual numbers; the final no-edge rule has no marginal ranking.',
    '## All six winners: pre-draw score ranks (1 = highest)',table(['Winner']+models,[[f'{n:02}']+[rank(n,m) for m in models] for n in [1,4,6,13,23,28]]),
    'Intervals denote exact-score ties whose original ordering was not retained. In particular, the missed winners 06, 23 and 28 did not form a strong top-ranked cluster.',
    '## #2339 winner coverage',table(['Model']+[f'Top {k}' for k in [5,6,8,10,12,15,20]],[[m]+[cov(m,k) for k in [5,6,8,10,12,15,20]] for m in models]),
    'Ranges reflect boundary ties, not uncertainty about the winning numbers. Exact tie-averaged values are in draw2339_topN_coverage.csv. A larger pool mechanically captures more winners; its random benchmark must also increase.',
    '## Hits, selected misses, and missed winners',table(['Group','Number','Full count','Last30','EW rate','Gap','Trend20−prior40','G proxy'],[[e['group'],f"{int(e['number']):02}",e['frequency'],e['last_30_count'],num(float(e['ew_rate'])),e['current_gap'],num(float(e['trend_20_vs_previous40'])),num(e['ensemble_marginal_score'])] for e in ev]),
    'The three hits had recent counts 6, 6 and 7, near-zero gaps and G proxy ranks 6, 5 and 2. However, selected miss 24 had an even stronger recent count (9), EW rate (0.2411) and G rank (1). Selected misses 14 and 38 ranked 19 and 11; missed winners 06, 23 and 28 ranked 23, 30 and 35. Thus a top-six rule could not have recovered the latter three; broadening to top 20 still would not include them. The strongest saved indicators did not cleanly separate hits from misses.',
    'These descriptive differences do not establish a rule that separates winners from losers. All nine numbers had zero retained pair-network score. The saved feature archive includes gap percentiles, volatility, all rolling frequencies, exact candidate memberships and model rank intervals. Number-level sensitivity was not saved pre-draw; ticket-level sensitivity cannot honestly be relabeled as number-level stability. See hit_miss_predraw_evidence.json and the untouched V1 candidate_sensitivity.json snapshot.',
    '## Frozen tracks scored',table(['Track','Main matches','Status'],[[t['track'],t['matches'],t['status']] for t in s['tracks']]),
    'Candidate rows are analytical pre-draw candidates, not separately registered prospective strategies. The sequential zero-data experiment is retained only as an invalidated historical artifact; its result is not reused. The complete-ticket zero-data Jev Challenger remains a distinct track.',
    '## Historical validation',
    '128 historical targets ending at #2338; warmup 50, last 40 targets are the previously examined confirmation segment. This is retrospective, post-#2339 hypothesis testing and **not a fresh holdout**. Finite methods and gates are documented in FORENSIC_PROTOCOL.md. All training precedes its target. The 79 distinct construction methods include six ranking variants, two structural penalties across top 8/10/12/15, uniform construction within broader pools, direct top six and larger G candidate search. Pure additive best-within-pool is identically top six, so it is not counted as independent corroboration.',
    'Top confirmation construction methods (descriptive ordering only):',table(['Method','Mean','95% block CI','3+','4+','Holm p','Δ vs B CI'],[[r['method'],num(r['mean']),ci(r['ci']),pct(r['three_plus']),pct(r['four_plus']),num(r['holm_p']),ci(r['paired_ci_vs_B'])] for r in sorted([r for r in cp if r['period']=='confirmation'],key=lambda r:-r['mean'])[:12]]),
    'All construction outcomes, 0–6 match rates, older/recent performance and paired contrasts are in construction_performance.json. No method passed the complete declared gate. No V2 is created.',
    'Historical confirmation number-discovery coverage:',table(['Model','Pool','Mean captured','Random mean','Median','3+','4+','5+','All6','Holm p'],[[r['model'],r['pool'],num(r['mean']),num(r['random_mean']),r['median'],pct(r['rates']['3']),pct(r['rates']['4']),pct(r['rates']['5']),pct(r['rates']['6']),num(r['holm_p'])] for r in rc if r['period']=='confirmation' and r['pool'] in [6,8,10,12,15,20]]),
    'Full/development/confirmation coverage, ≥2 through ≥6 capture, average precision and exact same-size random baselines are in ranking_coverage.json; per-origin rankings and construction outcomes are retained separately. Larger-pool coverage alone is not a construction advantage.',
    f"A fixed independent six-number ticket has exact-three probability {pct(rnd['single_ticket_exact3'])} and at-least-three probability {pct(rnd['single_ticket_atleast3'])}. These are per-ticket null probabilities, not a post-selection p-value for the best of an unspecified collection of played tickets. Across 20,000 random 40-draw controls, the mean-match 95% range was {ci(rnd['confirmation_mean_95'])}; random expected mean is 36/38 = 0.9474.",
    '## Explicit answers',
    'A. The table gives the pre-draw score ranks of 06, 23 and 28 under every applicable ranking. Original tie-break ranks are unavailable.\n\nB. Top 6/8/10/12/15/20 winner counts are shown above, with tied boundaries preserved.\n\nC. There is no corrected out-of-sample evidence that useful ranking information was systematically lost during ticket construction. Some larger pools captured more winners, as expected mechanically.\n\nD. Three matches are compatible with normal variation; this single prospective observation does not establish a predictive signal.\n\nE. No refinement passed the historical gate. Keep V1 frozen and gather fresh prospective evidence before promoting any challenger.',
    '## Reproduction and artifacts',
    'Run `python scripts/research/lotto_forensic.py` from the project root. This reads frozen V1 inputs and writes only this forensic directory. Do not alter the V1 snapshot, original workbook, original flat results or existing experiment freezes. The append-only prospective_ledger.jsonl is distinct from any future prediction record. Hash provenance is in v1_manifest.json. The source workbook was not modified.' ]
    write(o/'REPORT.md',out)

def super_report():
    o=R/'results/super_lotto';a=load(o/'audit.json');b=load(o/'baseline.json');p=load(o/'performance.json');cov=load(o/'coverage.json');cons=load(o/'construction_performance.json');rnd=load(o/'randomness.json');sens=load(o/'sensitivity.json');cs=load(o/'candidates.json');j=load(o/'jev_response.json');f=load(o/'prospective/prediction_1753.json');sel=f['selection'];ans=j['answers'];choice=ans['overall'];checks=load(o/'verification.json')
    out=['# SUPER LOTTO ANALYSIS',
    '## SUPER LOTTO PRIMARY',f"Main: **{ticket(sel['main'])}**\n\nSuper Ball: **{sel['super_ball']}**",
    f"Target **#{f['target_draw_id']}, {f['target_date']}**. Frozen PRE-DRAW at **{f['created_utc']}**. This is the one primary selection, candidate {sel['candidate_id']}, selected by the predeclared seeded no-edge rule. **No main or Super Ball model passed the statistical gate. No predictive superiority is claimed.**",
    '## Separation, rules and audit',
    'This analysis uses only the Super Lotto workbook and official Super Lotto verification. No Lotto draws, rankings, fitted weights, tickets or Jev responses enter its modelling or Jev state. Generic combinatorics/serialization helpers are shared, not game data. Rules: five unique main numbers from 1–35, plus one Super Ball from 1–10. [Official rules and schedule](https://supremeventures.com/game/super-lotto/) list Tuesday/Friday draws at 8:30 p.m. Jamaica time.',
    f"Recalculated **{a['original_records']} draws**, #{a['id_range'][0]}–#{a['id_range'][1]}, {a['date_range'][0]}–{a['date_range'][1]}. Workbook rows are descending; modelling uses ascending chronology. No missing/duplicate IDs, duplicate records, invalid dates, invalid values, repeated main numbers, derived-column discrepancies or frequency discrepancies. Main expected frequency is 25.142857, explaining the workbook's 25.1 rounding. Original SHA-256: `{a['sha256']}`.",
    'The official feed matched #1752 and contained no newer draw at the pre-draw check. External data and provenance are saved separately. Earlier workbook rows are screenshot transcriptions and were not all independently reconciled against official records; structural validation is not a guarantee against transcription errors. Both source workbooks remain unchanged.',
    '## Exact random baseline',
    table(['Main matches','Main probability','Same mains + SB','Same mains without SB'],[[i,pct(b['main_probabilities'][i]),f"{b['main_plus_SB_probabilities'][i]:.10f}",f"{b['main_without_SB_probabilities'][i]:.10f}"] for i in range(6)]),
    f"Expected main matches **{b['expected_main']:.6f}**; Super Ball accuracy **10%**. Jackpot probability **1 in {b['jackpot_denominator']:,}**. Main probabilities are C(5,k)C(30,5−k)/C(35,5); joint probabilities multiply by 0.1 under independent uniform draws. Main and SB models remain separate.",
    '## Features and relationships',
    'main_features.csv and super_ball_features.csv contain full/rolling/EW frequency, expected values, gap distributions and percentiles, trend and volatility. draw_structure.csv contains sums, mean/median, ranges, parity, low/high split, bands, consecutive/spacing/clustering, prior-draw overlap and last-digit properties. pairs.csv contains every pair, expectation, lift, rolling/half stability, gap and corrected enrichment. main_transitions.csv and super_ball_transitions.csv test conditional relationships. Triples are descriptive because expected counts are sparse; no triple-driven prediction is made. Typical-looking combinations are not inherently more likely as individual tickets.',
    '## Independent randomness tests',
    table(['Test','Observed','Raw p','Holm p','Conclusion'],[[r['test'],num(r['observed']),num(r['p']),num(r['holm_p']),r['classification']] for r in rnd['tests']]),
    '10,000 independently simulated histories; two-sided dispersion/repeat/location tests and upper-tail maximum/deviation tests. None detects a corrected deviation. Failure to reject randomness does not prove the generating process is uniform or rule out weak effects beyond this sample size.',
    '## Walk-forward design',
    '126 expanding-window targets after 50 warmup draws; 86 development and 40 retrospective confirmation. Main A–G select from 512 uniform candidate combinations; H is independently uniform. G learns only from earlier out-of-sample performance and freezes its weights at confirmation start. SB has seven separate models. Training-only Holm filtering controls pair and conditional enrichment. Flat E has no informative number ranking; F scores combinations only. G number rank is a marginal proxy; when flat its ties are neutrally seeded and not evidence of number-discovery skill.',
    'Confirmation performance (main mean matches; SB accuracy):',
    table(['Domain','Model','n','Mean','95% block CI','Older half','Recent half','Holm p','Gate'],[[r['domain'],r['model'],r['n'],num(r['mean']),ci(r['ci']),num(r['older']),num(r['recent']),num(r['holm_p']),r['qualifies']] for r in p if r['period']=='confirmation']),
    'All-target performance:',table(['Domain','Model','n','Total hits','Mean','0/1/2/3/4/5 rates','Holm p'],[[r['domain'],r['model'],r['n'],r['total'],num(r['mean']),'/'.join(pct(x) for x in r['rates']),num(r['holm_p'])] for r in p if r['period']=='all']),
    'Exact null mean-match tests use convolution of the appropriate hypergeometric distribution (SB Bernoulli 0.1). Five-draw circular block bootstrap CIs use 5,000 replicates. Corrections are separate predeclared main and SB families. performance.json retains all periods, rates and uncertainty; combined_performance.json contains every main×SB pairing as a 6×2 outcome count matrix. Joint comparisons are descriptive, not evidence-selected joint models.',
    '## Ranking coverage and construction',
    table(['Model','Pool','Mean winners','Random mean','3+','4+','All5','AP','Holm p'],[[r['model'],r['pool'],num(r['mean']),num(r['random_mean']),pct(r['three_plus']),pct(r['four_plus']),pct(r['all5']),num(r['AP']),num(r['holm_p'])] for r in cov if r['period']=='confirmation']),
    'coverage.json includes full/development/confirmation periods and exact same-pool random coverage probabilities. AP is mean average precision on all 35 numbers. E/F inapplicability is preserved. Corrected coverage tests do not establish an exploitable ranking edge.',
    'Top retrospective confirmation construction methods:',table(['Method','Mean','95% CI','Holm p'],[[r['method'],num(r['mean']),ci(r['ci']),num(r['holm_p'])] for r in sorted([r for r in cons if r['period']=='confirmation'],key=lambda r:-r['mean'])[:12]]),
    'Forty-four unique construction rules compare A/B/D/G top-five, exact structure-penalized combinations within top 7/8/10/12/15, and uniform draws within those pools. Pure additive optimization reduces to top five regardless of the larger pool. Construction results are exploratory; no corrected construction advantage is established. Full match distributions and per-origin tickets are saved.',
    '## Sensitivity and random controls',
    table(['Model','Min confirmation mean','Max confirmation mean','Best variant Holm p'],[[m,num(min(r['confirmation_mean'] for r in sens if r['model']==m)),num(max(r['confirmation_mean'] for r in sens if r['model']==m)),num(min(r['holm_p'] for r in sens if r['model']==m))] for m in sorted({r['model'] for r in sens})]),
    'Eleven perturbations cover rolling windows, EW decay, trend horizon, history length, pair threshold, ensemble weighting and search seed. These reuse the same outcomes and are not eleven independent replications; no best variant replaces the declared model. random_controls.json records 20,000 independent 40-draw null means. Candidate rank stability under unvalidated or flat objectives is not predictive robustness.',
    '## Analytical candidate shortlist and Jev',
    'The following is an analytical audit, not a set of additional recommended plays. Candidates are complete tickets, with at most three shared main numbers between any pair. Each profile records main/SB generator support, individual ranks, long/recent/gap/trend/pair/structure evidence, model agreement, sensitivity and counterevidence. The final no-edge rule chooses uniformly among these fixed candidates using seed 2026092109; it is not claimed to sample all playable tickets uniformly.',
    table(['ID','Main','SB','Main generator','SB generator','Jev Choice p','Robustness','Consensus','Quality','Stability'],[[c['id'],ticket(c['main']),c['super_ball'],c['main_generator'],c['SB_generator'],pct(choice['probabilities'][c['id']])]+[num(ans[c['id']+'_'+q]['score']) for q in ['robustness','consensus','quality','stability']] for c in cs]),
    f"Requested model `jev-latest`, returned **{j['model']}**. All **161** typed answers passed schema/probability checks. Jev preferred **{choice['choice']}**, Choice probability **{pct(choice['probabilities'][choice['choice']])}**, confidence **{num(choice['confidence'])}**. The complete distribution above and raw Score distributions/confidences are preserved in jev_response.json. Four Noul judgments per candidate are listed below; Noul has a probability, not a separate confidence.",
    table(['ID','Overfit/chance','Stable','Stronger than random','Single-family dependence'],[[c['id']]+[pct(ans[c['id']+'_'+q]['noul']) for q in ['overfit','stable','stronger','dependent']] for c in cs]),
    'Score scale is 0–4 with concrete supplied levels. Choice/Score confidence summarizes concentration in the model response; it is not a winning probability or external validation. Jev cannot override the statistical gate. A forced preference between unsupported candidates does not establish an edge. The primary is therefore the predeclared fallback rather than Jev’s favorite.',
    '## Prospective freeze and reproducibility',
    f"Primary {sel['candidate_id']} is recorded in prospective/prediction_1753.json, with timestamp, target, source/configuration/code hashes, exact full pre-draw rankings, Jev request hash and complete response, seed and model versions. The exclusive-create freeze script refuses to replace it. prospective/ledger.jsonl stores its SHA-256; future outcomes must be appended as new events. Local files are not cryptographically immutable storage; the digest and exclusive-write workflow make changes detectable.",
    f"Verification passed: {checks['origins']} valid backtest origins, independently recomputed scores, exact baselines, unchanged source workbook, and a future-data mutation test starting at #{checks['mutation_origin']} that leaves the target and earlier predictions unchanged. This test supplements code inspection; it is not a claim that every possible implementation defect has been excluded.",
    'From the project root: `python scripts/research/super_lotto.py` regenerates deterministic Super Lotto analytical outputs; `python scripts/research/verify_research.py` validates them; `python scripts/research/reports.py` renders both reports. The frozen prediction remains unchanged. `scripts/research/super_jev.mjs` uses the installed SDK and TYPESAFE_API_KEY environment variable; do not rerun Jev to search for a preferred answer. No key is stored in these results. The protected first response and prediction are the experiment of record.' ]
    write(o/'REPORT.md',out)

if __name__=='__main__':lotto();super_report();print('Both independent reports rendered.')
