import json,csv,hashlib,math
from pathlib import Path
from common import table,holm,save
R=Path(__file__).resolve().parents[2];V=R/'results/lotto/draw2340';O=R/'results/lotto/forensic_2340'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def fmt(x):return f'{x:.3f}'
def pct(x):return f'{100*x:.2f}%'
def ns(x):return ', '.join(f'{n:02}' for n in x) or '—'
def span(x):return str(x[0]) if x[0]==x[1] else f'{x[0]}–{x[1]}'
def ci(x):return ' to '.join(fmt(v) for v in x)
e=load(O/'number_evidence.json');cc=load(O/'candidate_outcomes.json');reach=load(O/'reachability.json');assoc=load(O/'jev_association.json');hist=load(O/'historical_discovery.json');comp=load(O/'compression_analysis.json');minimum=load(O/'minimum_discovery_pool.json');cov=list(csv.DictReader((O/'coverage_2340.csv').open(encoding='utf-8')));jev=load(O/'frozen_jev_analysis.json');f=load(V/'frozen.json');cs=load(V/'candidates.json');sensitivity=list(csv.DictReader((V/'sensitivity.csv').open(encoding='utf-8')))
# Top6 uniform is algebraically direct top6. Remove those five duplicated tests
# before the primary construction-family correction; keep raw audit outputs.
construction=[x for x in load(O/'construction_performance.json') if not x['method'].endswith(':top6:uniform')]
for period in ['all','development','confirmation']:
    sub=[x for x in construction if x['period']==period]
    for x,p in zip(sub,holm([x['p'] for x in sub])):
        x['holm_p']=float(p);x['passes_gate']=bool(period=='confirmation' and p<.05 and x['ci'][0]>36/38 and min(x['older'],x['recent'])>36/38 and x['paired_ci'][0]>0)
save(O/'construction_performance_unique.json',construction)
assert not any(x['passes_gate'] for x in construction)
models=['A_long','B_recent','C_gap','D_trend','G_marginal_proxy'];sizes=[6,8,10,12,15,20,25]
def coverage(model,k):
    x=next(r for r in cov if r['model']==model and int(r['pool'])==k);return f"{x['count']} ({ns(json.loads(x['winners']))})"
def ev(n):return next(x for x in e if x['number']==n)
selected=next(x for x in cs if x['id']=='C07');best=next(x for x in cc if x['id']=='C03');pref=next(x for x in cc if x['id']==jev['overall']['choice']);p0=math.comb(32,6)/math.comb(38,6)
out=['# LOTTO #2340 FORENSIC RESULTS',
'**No Lotto V2 is justified.** V1 preserved all six winners within the saved ensemble marginal top 20, and candidate C03 matched four. But the exact winning tuple was absent from the sampled source tickets, and the seeded no-edge final selection C07 matched zero. Historical tests do not show corrected repeatable ranking skill or construction advantage. No fresh Jev call, other-system comparison, or #2341 ticket was produced.',
'## Integrity and recorded outcome',
'Official result supplied by the user: **06, 08, 12, 14, 18, 31**, bonus **28**, draw #2340 on September 23, 2026. Frozen Codex primary **05, 11, 16, 24, 27, 34**: **0/6 mains**. Bonus is recorded only as an official outcome; V1 did not predict it and no retrospective bonus score is assigned.',
'Verified before analysis: all **14 hashes** embedded in the #2340 freeze, plus the ledger checksum of frozen.json. Target #2340, cutoff #2339, seed 20260919, candidate pool, saved rankings, Jev request/response and original code all match. Every file in the #2340 directory was additionally hashed for preservation during this forensic run. Auxiliary CSVs not individually covered by the original freeze are identified by their present preservation hashes; these hashes do not retroactively create original checksums.',
'The result was appended once to the Lotto ledger without altering prior entries. No Claude, other branch, other session or other system #2340 prediction/analysis was inspected. The outcome is treated as user-supplied official information; no claim is made of a new independent archive fetch.',
'## A. Exact saved pre-draw positions',
table(['Number','Role']+models,[[f"{x['number']:02}",x['group']]+[x['models'][m]['saved_rank'] for m in models] for x in e]),
'These are actual stored orders from refreshed_rankings.json, not post-draw ranks. Exact-score tie intervals and scores are retained in number_evidence.json. **G_marginal_proxy is not the complete G_ensemble ticket objective**: it is the weighted individual-score proxy and omits the structure component. The active G ticket objective combines standardized whole-ticket values. The no-edge final selection itself used no marginal-number ranking.',
'E_pairs had all-zero scores. Its saved tie order for winners 06/08/12/14/18/31 was 27/15/11/29/25/10; those positions are arbitrary and non-informative. F_structure ranks whole combinations, not individual numbers. B_recent blends last-30 frequency and EW frequency; no standalone EW ranking was frozen. Transition statistics were descriptive, not a predictive model. There was no hazard model, separate adaptive-ensemble ranking, or saved final H_random 38-number ordering. Do not substitute newly invented positions for these unavailable fields. The existing learned ensemble is G, not an additional model.',
'## B. Exact #2340 top-N winner coverage',
table(['Model']+[f'Top {k}' for k in sizes],[[m]+[coverage(m,k) for k in sizes] for m in models]),
'Cells show count (exact winner identities). The full file includes the flat E tie order, clearly marked uninformative. E/F are not meaningful discovery rankings. Expected random coverage for the seven pool sizes is '+', '.join(f'{6*k/38:.3f}' for k in sizes)+'.',
table(['Model','Smallest N for 3','For 4','For 5','For all 6'],[[x['model'],x['top_for3'],x['top_for4'],x['top_for5'],x['top_for6']] for x in minimum if x['informative']]),
'## C–E. Discovery, construction and mechanical reachability',
'**Yes, the saved G marginal top 20 contained all six winners.** A_long needed top 24, B_recent top 21, D_trend top 33 and C_gap top 36. Top 20 is computationally enumerable (38,760 six-number combinations), but it was a diagnostic pool, not an active V1 source constructor or a validated shortlist.',
'Mechanical answers:\n\nA. All six numbers were individually present in the shared 4,096-tuple source sample, which covered 1–38. All six were also represented somewhere across the final 20 candidates.\n\nB. V1 did **not** use top-N marginal pools as its active final construction source. G top 20 is a saved diagnostic, not evidence that V1 enumerated those 38,760 combinations.\n\nC. With the exact frozen seed/sample, V1 could not produce the winning combination: it was absent from all 4,096 source tuples (4,095 unique) and the one H fallback sample. V1 copies complete sampled tuples; it does not freely recombine their component numbers. The generic uniform sampler permits the combination in principle, but that is different from reachability in this frozen run.\n\nD. Its actual absence occurred before scoring: there is no basis to claim structure optimization, ranking score or diversity rejected that exact tuple. Hypothetically, after C03 was accepted, its four shared winning numbers would conflict with V1’s maximum-three inter-candidate overlap rule; that is a later counterfactual constraint, not the recorded cause of omission. The requested additional-ticket overlap rule would have allowed the winning tuple because it shares only 14 with the previous primary.',
'Source replay used only the frozen code, seed and #2339-cutoff inputs and reproduced **all 20 candidates exactly**, including generating method. Replayed source tuples and selected indices are saved separately. No candidate was inserted, changed or generated for a future draw.',
'## J. Why the six selected losers were favored',
table(['Number','Role','Full count','Last30','EW rate','Gap','Gap percentile','Gap rank','Trend z','G score'],[[f"{x['number']:02}",x['group'],x['features']['frequency'],x['features']['last_30_count'],fmt(float(x['features']['ew_rate'])),x['features']['current_gap'],fmt(float(x['features']['current_gap_percentile'])),x['models']['C_gap']['saved_rank'],fmt(x['models']['D_trend']['score']),fmt(x['models']['G_marginal_proxy']['score'])] for x in e]),
'C07 was generated by **C_gap**. Selected numbers 16, 11, 34, 27 and 05 had long gaps (21, 17, 16, 12 and 11 draws) and gap ranks 1, 2, 3, 5 and 8. Winners 06 and 18 had gaps 0 and 1 and ranked 36 and 31 under gap. Thus the gap objective favored long-absent losing numbers over those recent winners. This explains the pre-draw heuristic’s behavior; it does not establish that absence is predictive or that reversing gap scores would help.',
'The final system did **not** establish that C07 was superior to the winners or other candidates. No method passed the empirical gate, so C07 was selected uniformly from the 16 diversified eligible candidates using the fixed seed. Its G ranks were 38, 33, 37, 3, 36 and 31; most selected losers were actually weak under the ensemble proxy. Number 24 was the exception, with strong frequency/recent evidence but no realized hit. Candidate optimization over a finite sample and diversification explain why C07 is not simply the six highest gap ranks.',
f"C07 had complete-ticket support labels {', '.join(selected['contributing_models'])}; those correlated, unvalidated labels are not independent model confirmation. Its saved sensitivity rank range was {selected['generator_sensitivity_rank_min']:.0f}–{selected['generator_sensitivity_rank_max']:.0f}, with top-quartile fraction {pct(selected['sensitivity_top_quartile_fraction'])}. Number-level sensitivity was not saved. All twelve examined numbers had zero corrected pair/network score. The saved transition rows from latest-draw triggers to these numbers all had Holm p=1; no transition signal drove V1 selection.",
table(['Number','Top-12 ranking labels','Candidate appearances','Candidate IDs'],[[f"{x['number']:02}",', '.join(x['top12_informative_families']) or 'None',x['candidate_appearances'],', '.join(x['candidate_memberships'])] for x in e]),
'The model labels above share data and are not independent families. number_evidence.json retains all saved rolling frequencies, EW rate, current/complete gaps, percentile, volatility, trend, scores, exact rank/tie positions, candidate memberships, candidate-level sensitivity and relevant saved transition rows. No new hazard score, causal account, or per-number stability series is invented.',
'## F–H. Complete frozen candidate scoring',
'Four of the 20 frozen candidates were excluded by the requested additional-ticket overlap limit before Jev. Their missing Choice probabilities are **N/A**, not zero. Jev evaluated the remaining 16 complete tickets.',
table(['ID','Frozen numbers','Generator','Hits','Matched','Jev Choice','Eligible'],[[x['id'],ns(x['numbers']),x['generator'],x['matches'],ns(x['matched']),'N/A' if x['choice_probability'] is None else pct(x['choice_probability']),x['eligible_for_additional_ticket']] for x in cc]),
table(['Main matches','Candidate count'],[[i,sum(x['matches']==i for x in cc)] for i in range(7)]),
'**Best: C03**, matching **06, 08, 12 and 18** (4/6). It was eligible for the additional ticket and received Jev Choice probability 0%. **Final C07:** zero matches, tied positions **17–20 of all 20**, or **14–16 among the 16 eligible candidates**. All six eventual winners appeared somewhere in the full shortlist; none was completely missing. No candidate held five or six winners.',
f"**Jev preferred {pref['id']}**, matching **{ns(pref['matched'])}** ({pref['matches']}/6). Frozen model `{jev['model']}`, Choice probability **{pct(jev['overall']['probabilities'][pref['id']])}**, confidence **{fmt(jev['overall']['confidence'])}**. The final C07 was not Jev’s selection: the no-edge fallback overrode model preference by design. Neither Jev nor the policy chose the hindsight-best C03.",
'## I. Frozen Jev judgments and realized association',
table(['ID','Robustness','Consensus','Quality','Overfit/chance','Stable','Stronger than random','Single-model dependence'],[[x['id']]+[fmt(x['saved_jev'][k]['score']) for k in ['robustness','consensus','quality']]+[pct(x['saved_jev'][k]['noul']) for k in ['overfit','stable','stronger','dependent']] for x in cc if x['saved_jev'] is not None]),
f"For the 16 evaluated options, tie-aware Spearman correlation of Choice probability with realized matches is **{assoc['spearman']:.3f}**. Whole-uniform-draw simulation preserving ticket overlap (20,000 draws) gives descriptive two-sided p **{assoc['two_sided_mc_p']:.3f}**. Choice-weighted matches were {assoc['choice_weighted_matches']:.3f}, versus unweighted eligible-candidate mean {assoc['unweighted_matches']:.3f}. This is not a meaningful demonstrated relationship in one draw. It does not establish that Jev is systematically good or bad at forecasting.",
'The complete frozen Choice distribution is shown in the candidate table. Raw Score distributions/confidences and Nouls are preserved in frozen_jev_analysis.json. Choice probabilities reflect the supplied evidence-preference question, not lottery-winning probabilities; confidence describes distribution concentration. [Current TypeSafe confidence documentation](https://docs.typesafe.ai/confidence) was consulted. No new Jev request was made.',
'## What happened versus what is repeatable',
f"For this draw, the broad G ranking contained all winners, the sampled source omitted their complete tuple, a four-hit candidate existed, and the seeded final rule picked a zero-hit candidate. These are realized construction/selection limitations, not proof of a predictive ranking edge. A fixed uniform six-number ticket has zero-main-match probability **{pct(p0)}**, so 0/6 is ordinary under the random null.",
'Descriptively this combines partial number discovery, complete-ticket source coverage failure, and hindsight selection loss, with ordinary random variation. It is not a failure to represent the winners individually, nor can the final miss be attributed to Jev choosing C07. The historical tests below address repeatability rather than explaining the result with a newly invented rule.',
'## Historical number discovery through #2339',
'129 strict expanding-window targets after 50 warmup draws. All features use prior targets only; learned ensemble weights are taken from the corresponding saved pre-target V1 record. Ranking orders for historical targets were reconstructed from frozen prior data and original tie rules; they are not mislabeled as originally saved full orders. #2340 is excluded. Final 40 targets are reused retrospective confirmation, not a fresh holdout.',
table(['Pool','Random mean','Random 3+','Random 4+','Random 5+','Random all6'],[[k,fmt(6*k/38)]+[pct(next(r for r in hist if r['pool']==k)['events'][str(t)]['random_rate']) for t in [3,4,5,6]] for k in sizes]),
table(['Model','Pool','Confirmation mean','3+','4+','5+','All6','Mean Holm p','Best event Holm p'],[[x['model'],x['pool'],fmt(x['mean'])]+[pct(x['events'][str(k)]['rate']) for k in [3,4,5,6]]+[fmt(x['holm_p']),fmt(min(y['holm_p'] for y in x['events'].values()))] for x in hist if x['period']=='confirmation']),
'No corrected repeatable discovery advantage was found. All full-period and confirmation mean-coverage and event-family Holm p-values were 1.000. Exact hypergeometric pool-size references and exact event-tail tests account for larger pools mechanically capturing more winners. Full/development/confirmation counts and rates are in historical_discovery.json. Random ordering is a control; flat E and combination-only F are not counted as serious number-discovery models.',
'## K. Historical discovery-to-construction loss',
'For a pool capturing q eventual winners, the hindsight best possible six-number ticket captures q. This oracle is **not an executable forecast**. A uniformly chosen six from that same m-number pool captures 6q/m on average and loses q(1−6/m) relative to the oracle. Under a random pool plus random nested ticket, expected loss is 6(m−6)/38. Therefore a large oracle-to-ticket gap arises even when rankings contain no usable information.',
'For the G marginal proxy, confirmation results were:',
table(['Pool','Constructor','Pool winners','Ticket hits','Oracle loss','Conditional random loss','Excess hits vs conditional random','Holm p'],[[x['pool'],x['constructor'],fmt(x['oracle_mean']),fmt(x['actual_mean']),fmt(x['oracle_loss_mean']),fmt(x['conditional_uniform_loss_mean']),fmt(x['conditional_excess_hits']),fmt(x['holm_p'])] for x in comp if x['period']=='confirmation' and x['model']=='G_marginal_proxy']),
'Example: G top 20 captured 3.175 winners per confirmation draw. Its structure constructor retained 0.975, an oracle gap of 2.200. Uniform construction conditional on that same pool coverage would lose 2.2225 on average. Thus the large raw gap is almost exactly what ordinary compression predicts; it does not demonstrate discarded predictive information. Direct top six retained 1.100, but its conditional excess also failed correction.',
'All models, pools and constructors are reported for full/development/confirmation in compression_analysis.json, with conditional exact convolution tests, corrected p-values and block CIs. Random_compression_controls.json contains 20,000 nested random-pool/random-ticket 40-target simulations per pool size. No corrected conditional construction advantage is established. These corresponding constructors always select inside their discovery pool; the original V1 512-sample tickets are not falsely treated as constrained top-N constructions.',
'## L–M. Predeclared refinements and V2 decision',
'Before the historical tests, PROTOCOL.txt fixed a finite family: direct top six, uniform selection within top 6/8/10/12/15/20/25, exact additive-plus-structure search within top 8/10/12/15/20, larger G source search, equal ensemble weights and exclusion of inactive G components. The raw audit has 68 method labels; five top6-uniform labels are algebraically identical to direct top6 and are removed for the **63-rule primary Holm correction**. None uses #2340 to fit parameters. Pure additive maximization within any larger pool is already direct top six, so it is not counted as a new success.',
table(['Method','Confirmation mean','95% block CI','Raw p','Holm p','Δ vs V1 G','Paired CI','Pass'],[[x['method'],fmt(x['mean']),ci(x['ci']),fmt(x['p']),fmt(x['holm_p']),fmt(x['paired_delta']),ci(x['paired_ci']),x['passes_gate']] for x in sorted([x for x in construction if x['period']=='confirmation'],key=lambda x:-x['mean'])[:12]]),
'The strongest raw result was D_trend within top 10 with structure penalty 0.25: mean 1.225, raw p=0.024, but Holm p=1.000 after the declared search. A positive paired contrast against a weak V1 G benchmark does not override the failed corrected random-null gate. No method passed the gate, so no favorable post-hoc stability search was used to rescue it. Existing frozen sensitivity variants also remain exploratory rather than promoted models.',
'**No Lotto V2 is justified.** V1 remains unchanged. No #2341 prediction, candidate recommendation or fresh prospective Jev call was generated.',
'## Files and reproducibility',
'All forensic outputs are separate under results/lotto/forensic_2340/. The only change outside that directory is the requested append-only outcome event in results/lotto/prospective_ledger.jsonl and new forensic scripts/log. integrity.json records verified original hashes; verification.json confirms preservation, exact candidate replay, cutoff and zero new Jev calls. Main evidence, exact coverage, minimum pool sizes, every candidate outcome, original Jev judgments, reachability, historical discovery, construction, compression and random controls are saved as machine-readable artifacts.',
'From the project root run `python scripts/research/lotto_2340_forensic.py`, then `python scripts/research/report_lotto_2340.py`. These never run the original analysis main entry point, overwrite the frozen run, or call Jev. The ledger outcome append is idempotent. Supporting input preservation is checked again after report rendering.'
]
(O/'REPORT.md').write_text('\n\n'.join(out)+'\n',encoding='utf-8')
integrity=load(O/'integrity.json');assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in integrity['protected_hashes'].items())
assert all(not x['passes_gate'] for x in construction)
save(O/'v2_decision.json',dict(created=False,conclusion='No Lotto V2 is justified.',unique_methods=63,qualified_methods=[],primary_correction_file='construction_performance_unique.json',no_2341_generated=True))
print('Report saved; 63 unique construction rules fail the gate; all frozen inputs unchanged.')
